# 1. Numpy and Array

- 수치 data 를 다루는데 효율적이고 높은 성능 제공

- 각종 수학적 함수 제공

- Python scientific library 들이 Numpy 기반으로 구축

### ndarray

- n-dimensional array (다차원 배열 객체) 로 구성 

In [1]:
import sys
import numpy as np

In [2]:
# 스칼라
x = 6
x

6

In [3]:
a = np.array([1])
a, a.shape

(array([1]), (1,))

In [4]:
# 벡터
x = np.array([1,2,3])

print("x = ", x)
print("dimension of x is {}".format(x.shape))

x =  [1 2 3]
dimension of x is (3,)


In [5]:
np.argmax(x)

2

In [6]:
# matrix
y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("array dimension {}".format(y.shape))
print("array size {}".format(y.size))
print("argmax {}".format(np.argmax(y, axis=1)))

array dimension (3, 3)
array size 9
argmax [2 2 2]


In [8]:
x = np.array([[[1, 2, 3], 
               [3, 2, 5]], 
              [[1, 7, 8], 
               [5, 4, 6]]])

x, x.shape

(array([[[1, 2, 3],
         [3, 2, 5]],
 
        [[1, 7, 8],
         [5, 4, 6]]]),
 (2, 2, 3))

## Indexing / Slicing

In [9]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(arr[:2, 1:])

[[2 3]
 [5 6]]


In [11]:
arr[2]

array([7, 8, 9])

In [12]:
arr[2, :]

array([7, 8, 9])

In [13]:
arr[2:, :]

array([[7, 8, 9]])

### 전치행렬 (Transposed Matrix)

In [16]:
# matrix transpose
A = np.arange(9).reshape((3,3))
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
print(A.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [18]:
A = np.array(range(10)).reshape((2,5))
print(A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
B = A.T
print(B)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [20]:
print(A.shape)
print(B.shape)

(2, 5)
(5, 2)
