# 020. LSTM/GRU input/output shape

- return_sequences = False, True 일 때의 output 비교

- return_state = False, True 일 때의 internal state output 비교

- Bidirectional LSTM/GRU 의 output 비교

In [1]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Bidirectional, GRU
import numpy as np

T = 4   #Time Steps
D = 2   #features
U = 3   #LSTM units

X = np.random.randn(2, T, D)
print(X.shape)
X

(2, 4, 2)


array([[[-0.47755444,  0.53344403],
        [ 0.04441918, -0.53640228],
        [ 0.3649314 , -0.16941602],
        [-0.01985527, -1.2878142 ]],

       [[-1.1153807 ,  0.7491309 ],
        [ 1.07933941,  0.99181957],
        [-0.10751697, -0.04563862],
        [-1.69873672, -1.07844117]]])

# LSTM

## return_sequences

In [11]:
def lstm(return_sequences=False):
    input_ = Input(shape=(T, D))
    rnn = LSTM(U, return_sequences=return_sequences)
    x = rnn(input_)
    
    model = Model(inputs=input_, outputs=x)

    return model.predict(X)

print("---- return_sequences=False ----> last timestep 의 outout only")
lstm_out = lstm(return_sequences=False)
print(lstm_out.shape)
print(lstm_out)
print("\n---- return_sequences=True ----> 모든 timestep 별 output")
lstm_out = lstm(return_sequences=True)
print(lstm_out.shape)
print(lstm_out)

---- return_sequences = False ----> last timestep 의 outout only
(2, 3)
[[-0.16318087 -0.26601046 -0.14620705]
 [-0.07774807 -0.05002573  0.07581867]]

---- return_sequences = True ----> 모든 timestep 별 output
(2, 4, 3)
[[[-0.07946784  0.11535564  0.0553988 ]
  [-0.02864506  0.00935064 -0.02670388]
  [ 0.02913543 -0.0196745  -0.06104105]
  [ 0.10263456 -0.14729246 -0.2132257 ]]

 [[-0.11479531  0.20007658  0.07528973]
  [-0.08222293  0.15899599  0.03468641]
  [-0.09070182  0.18347023  0.04571557]
  [-0.10351434  0.05059555  0.08385997]]]


## return_state

In [16]:
def lstm(return_state=False):
    input_ = Input(shape=(T, D))
    rnn = LSTM(U, return_state=return_state)
    x = rnn(input_)
    
    model = Model(inputs=input_, outputs=x)
    
    if return_state:
        o, h, c = model.predict(X)
        print("o :", o, o.shape)
        print("h :", h, h.shape)
        print("c :", c, c.shape)
    else:
        o = model.predict(X)
        print("o :", o, o.shape)

print("---- return_state=False ----> outout only")       
lstm(return_state=False)
print("\n---- return_state=True ----> outout, hidden state, cell state all")      
lstm(return_state=True)

---- return_state=False ----> outout only
o : [[-0.21021575 -0.08120792  0.12483135]
 [-0.12281858 -0.13684325 -0.05307796]] (2, 3)

---- return_state=True ----> outout, hidden state, cell state all
o : [[-0.20073107 -0.04531339  0.19160178]
 [-0.06412257 -0.01707803 -0.17108546]] (2, 3)
h : [[-0.20073107 -0.04531339  0.19160178]
 [-0.06412257 -0.01707803 -0.17108546]] (2, 3)
c : [[-0.34282696 -0.08009572  0.39867294]
 [-0.19462532 -0.04609442 -0.29620636]] (2, 3)


# Bidirectional LSTM

In [17]:
def lstm(return_sequences=False, return_state=False):
    input_ = Input(shape=(T, D))
    rnn = Bidirectional(LSTM(U, return_state=return_state, return_sequences=return_sequences))
    x = rnn(input_)
    
    model = Model(inputs=input_, outputs=x)
    if return_state:    
        o, h1, c1, h2, c2 = model.predict(X)
        print("o :", o, o.shape)
        print("h1 :", h1, h1.shape)
        print("c1 :", c1, c1.shape)
        print("h2 :", h2, h2.shape)
        print("c2 :", c2, c2.shape)
    else:
        o = model.predict(X)
        print("o :", o, o.shape)

print("---- return_sequences = False ----")
lstm(return_sequences=False)
print()
print("---- return_sequences = True ----")
lstm(return_sequences=True)
print()
print("---- return_state = True ----")
lstm(return_state=True)

---- return_sequences = False ----
o : [[-0.01018252  0.02526386 -0.05576031 -0.04137729  0.0201376  -0.05487873]
 [-0.04829004 -0.13877171 -0.05340841  0.03058968 -0.06682337  0.1672945 ]] (2, 6)

---- return_sequences = True ----
o : [[[ 0.12999731 -0.03674179 -0.09858713  0.10842701  0.12110278
   -0.01285514]
  [ 0.01870246 -0.02648847 -0.04283405  0.13549691  0.10501228
    0.02214192]
  [-0.03939334  0.01226906  0.01579049  0.10341877  0.0648084
    0.03413119]
  [-0.1944102  -0.03361392  0.11135019  0.1046778   0.11959911
   -0.04540014]]

 [[ 0.22541696 -0.0975435  -0.14340189 -0.1681302   0.17023392
   -0.03349925]
  [ 0.16892476  0.01646093 -0.16239789 -0.32090512  0.07345697
    0.08254638]
  [ 0.16855027  0.00072312 -0.10663471  0.08394167  0.23880082
   -0.10510502]
  [ 0.113301   -0.0851797  -0.08570216  0.04931038  0.34333476
   -0.15008117]]] (2, 4, 6)

---- return_state = True ----
o : [[-0.14850013  0.1280502   0.08173151 -0.02086774 -0.02952189 -0.04328517]
 [ 0.1147

# GRU

In [18]:
def gru(return_sequences=False, return_state=False):
    input_ = Input(shape=(T, D))
    rnn = GRU(U, return_state=return_state, return_sequences=return_sequences)
    x = rnn(input_)
    
    model = Model(inputs=input_, outputs=x)
    
    if return_state:    
        o, h = model.predict(X)
        print("o :", o, o.shape)
        print("h :", h, h.shape)
    else:
        o = model.predict(X)
        print("o :", o, o.shape)

print("---- return_sequences = False ----")
gru(return_sequences=False)
print()
print("---- return_sequences = True ----")
gru(return_sequences=True)
print()
print("---- return_state = True ----")
gru(return_state=True)

---- return_sequences = False ----
o : [[-0.48924664 -0.2111119   0.3849383 ]
 [ 0.17082742  0.08165774 -0.17002739]] (2, 3)

---- return_sequences = True ----
o : [[[ 0.09928149 -0.08198903  0.17867956]
  [ 0.07627372  0.04187306  0.08946487]
  [-0.06383143  0.10426279 -0.07278779]
  [ 0.08637559  0.16656616 -0.01763822]]

 [[ 0.26051247 -0.1136561   0.3998354 ]
  [-0.35812217  0.06048363 -0.28610283]
  [-0.12541656 -0.07674465 -0.05799039]
  [ 0.25643075 -0.15420943  0.30075136]]] (2, 4, 3)

---- return_state = True ----
o : [[ 0.30038622  0.31155238 -0.3713353 ]
 [-0.19383506  0.68660265  0.45440573]] (2, 3)
h : [[ 0.30038622  0.31155238 -0.3713353 ]
 [-0.19383506  0.68660265  0.45440573]] (2, 3)


# Bidirectional GRU

In [19]:
def gru(return_sequences=False, return_state=False):
    input_ = Input(shape=(T, D))
    rnn = Bidirectional(GRU(U, return_state=return_state, return_sequences=return_sequences))
    x = rnn(input_)
    
    model = Model(inputs=input_, outputs=x)
    if return_state:    
        o, h1, h2 = model.predict(X)
        print("o :", o, o.shape)
        print("h1 :", h1, h1.shape)
        print("h2 :", h2, h2.shape)
    else:
        o = model.predict(X)
        print("o :", o, o.shape)

print("---- return_sequences = False ----")
gru(return_sequences=False)
print()
print("---- return_sequences = True ----")
gru(return_sequences=True)
print()
print("---- return_state = True ----")
gru(return_state=True)

---- return_sequences = False ----
o : [[-0.3860831  -0.20975839  0.11751009  0.0318537  -0.14323047 -0.04306468]
 [-0.5617771   0.14893825  0.16889827  0.27930453 -0.36701122 -0.01523402]] (2, 6)

---- return_sequences = True ----
o : [[[ 0.15692885 -0.19612339  0.04121208  0.01676249 -0.09819848
    0.04316086]
  [-0.10996332  0.04994248  0.00965715  0.19684957 -0.01024638
    0.06650266]
  [-0.10447524  0.09913532 -0.00518088  0.07014292  0.04088584
    0.01311663]
  [-0.30324787  0.4107794  -0.01332629  0.31907374 -0.0740199
    0.1949275 ]]

 [[ 0.22164576 -0.3209663   0.09942935 -0.0490145   0.05651551
   -0.05976145]
  [ 0.2624231  -0.39245978  0.01401869 -0.4206627   0.44044474
   -0.19562906]
  [ 0.03563983 -0.22742748 -0.00505878  0.15073411 -0.10658781
    0.1697227 ]
  [-0.15652561  0.27548414  0.0772383   0.39501557 -0.17081514
    0.3994767 ]]] (2, 4, 6)

---- return_state = True ----
o : [[ 0.30656314 -0.38910866  0.48634368 -0.11563462  0.03347948  0.08398932]
 [ 0.1301